### ISSUE TITLE
Source map not working for SCSS files

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#104]
### Display Scss Information
-No information about scss file 
-No information about map

**Not Working**
<img width="512" alt="screenshot 2018-09-19 11 22 42" src="https://user-images.githubusercontent.com/12101846/45759591-9e7ed680-bbfe-11e8-9ded-3570d33d8c0f.png">
**Working**
<img width="512" alt="screenshot 2018-09-19 11 22 57" src="https://user-images.githubusercontent.com/12101846/45759599-a2aaf400-bbfe-11e8-83ee-81948d666c20.png">

**Branch:** styles-data
**Refe:** 
https://www.google.com.ar/search?rlz=1C5CHFA_enAR800AR800&ei=uF2iW5rCDsqowATj66qwAQ&q=angular+SourceMaps+scss+%3Cstyles%3E...%3C%2Fstyles%3E&oq=angular+SourceMaps+scss+%3Cstyles%3E...%3C%2Fstyles%3E&gs_l=psy-ab.3...8150.8150.0.8612.1.1.0.0.0.0.71.71.1.1.0....0...1c.1.64.psy-ab..0.0.0....0.p3n7lR8Okv0
https://github.com/angular/angular-cli/issues/2020

**Comment by Agusx1211** [comment]
Comment request @nicolaswww, is this still an issue?

**Comment by nicolaswww** [comment]
This works correctly in development environment since 0.2.0
