### ISSUE TITLE
VM execution error.

### ISSUE THREAD

**Issue by javiervelaz** [ripio/rcn-loans#105]
I have "VM execution error." error message when a try to make a lend.
there is any solution for this issue ?

**Comment by javiervelaz** [comment]
![rcn](https://user-images.githubusercontent.com/4335443/46044406-0d719900-c0f1-11e8-8e32-43710f30cf1e.png)

**Comment by Agusx1211** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crear una herramienta para monitorear el estado de Oracles](https://trello.com/c/KjCx8lq0/15-crear-una-herramienta-para-monitorear-el-estado-de-oracles)

**Comment by Agusx1211** [comment]
There was a problem with the Oracle provided by Ripio, and it had connection issues between  09/24/2018 @ 8:35 pm UTC and 09/26/2018 @ 2:59 pm UTC

The problem is fixed, and the lend button should be working.
