### ISSUE TITLE
Redesign Detail Cosigner Decentraland

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#108]
### Detail Cosigner Decentraland
-Redesign

![screenshot 2018-10-02 13 56 38](https://user-images.githubusercontent.com/12101846/46364023-05fb4400-c64b-11e8-88a2-d1df970e9edc.jpg)

**Branch:** decentraland-detail
**Refe:** #107 

https://rcn.loans/loan/153

**Comment by devbold** [comment]
![screenshot 2018-10-02 13 25 03](https://user-images.githubusercontent.com/12101846/46373841-7e6efe80-c665-11e8-9aa1-62715598ce8b.jpg)

**Comment by Agusx1211** [comment]
Merged #109
