### ISSUE TITLE
Notifications: Transaction Notifications

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#110]
### Notifications
-Design a Transaction Notifications Component for Header

**Refe:** 
![screenshot 2018-10-11 15 12 22](https://user-images.githubusercontent.com/12101846/46828570-e3b3a580-cd71-11e8-93c2-ecdf59ac11ed.jpg)

**Branch:** notification-component

**Comment by devbold** [comment]
### Notifications Component

## Main Version
![screen shot 2018-12-04 at 13 03 42](https://user-images.githubusercontent.com/12101846/49455114-5dda3680-f7c5-11e8-8a25-29d16cf30e05.jpg)
![screen shot 2018-12-04 at 13 07 03](https://user-images.githubusercontent.com/12101846/49455234-89f5b780-f7c5-11e8-98fe-3036c39733af.jpg)

## Mobile Min Version
![screen shot 2018-12-04 at 13 04 12](https://user-images.githubusercontent.com/12101846/49455118-5e72cd00-f7c5-11e8-8fa2-f8d1e0d2127b.jpg)

## Variant Version
![screen shot 2018-12-04 at 13 04 02](https://user-images.githubusercontent.com/12101846/49455115-5dda3680-f7c5-11e8-8230-15200e522256.jpg)

## Variant Version
![screen shot 2018-12-04 at 13 04 23](https://user-images.githubusercontent.com/12101846/49455119-5e72cd00-f7c5-11e8-983f-7ab13e89fa44.jpg)

@Agusx1211

**Comment by devbold** [comment]
### Notifications Component v2.0

**Main Version**

![screen shot 2018-12-05 at 17 21 43](https://user-images.githubusercontent.com/12101846/49548731-6d40a900-f8c5-11e8-8c7b-782434d16b70.jpg)
![screen shot 2018-12-05 at 17 22 29](https://user-images.githubusercontent.com/12101846/49548732-6d40a900-f8c5-11e8-9bfc-6df47c25b728.jpg)

@Agusx1211

**Comment by Agusx1211** [comment]
@devbold It looks amazing! I really like the V2
