### ISSUE TITLE
Request Loan Form 

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#118]
### Request Loan ModuleShould be autonomous
-Include all components declarations
-Include all sevices
-Integrate a Request Button
-Easy/Intuitive User Experience
-Include minimalist icon 
-Material Design

![rcn-loans--createloan-01](https://user-images.githubusercontent.com/12101846/47455112-63e0fe80-d7a7-11e8-99bc-ccc8aa262058.jpg)

**Refe:** #115 
**Branch:** loan-request-form

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
