### ISSUE TITLE
Request duration only visible on card, not in detail

### ISSUE THREAD

**Issue by Agusx1211** [ripio/rcn-loans#146]
The duration of the loan is not visible on the request detail, only on the /requests page.

Ej:
https://mainnet.rcn.loans/loan/394

![image](https://user-images.githubusercontent.com/12701942/48088867-64e04a00-e203-11e8-818e-ced56e2b0121.png)
![image](https://user-images.githubusercontent.com/12701942/48088894-7164a280-e203-11e8-9860-418cd7fb2666.png)

**Comment by camiladelaserna** [comment]
FIxed and merged to 'master'.
![Captura de pantalla de 2019-05-16 14-37-04](https://user-images.githubusercontent.com/47121161/57875038-509b8c00-77e8-11e9-8bef-44493ca4bb4f.png)
