### ISSUE TITLE
Share Loans

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#175]
### Design interface to send and share Loans
-Social Media
-Chats messeges

![rcn-loans--requested-00](https://user-images.githubusercontent.com/12101846/49101495-14359d00-f255-11e8-98b4-50327d30689e.jpg)

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
