### ISSUE TITLE
Create Lend progress button

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#177]
### Create Lend progress button to mark a success state
-Create success button
-Create progress bar
-Create animation
-Consider making transitions and fluid animation between states

![screen shot 2018-12-03 at 13 48 26](https://user-images.githubusercontent.com/12101846/49388307-79303d80-f702-11e8-81f7-7a52ce363e38.jpg)
![screen shot 2018-12-03 at 13 48 31](https://user-images.githubusercontent.com/12101846/49388309-79303d80-f702-11e8-87da-4ad69c291d44.jpg)
![screen shot 2018-12-03 at 13 48 39](https://user-images.githubusercontent.com/12101846/49388312-79303d80-f702-11e8-90cf-c8a805d20fc5.jpg)

**Branch:** lend-progress-button
**Refe:** 
https://material.io/archive/guidelines/components/progress-activity.html#progress-activity-types-of-indicators
https://angular.io/guide/animations
https://tympanus.net/Tutorials/CircularProgressButton/
https://material.angular.io/components/progress-spinner/overview
https://netbasal.com/animate-dynamic-components-in-angular-10681438bdd4
https://medium.freecodecamp.org/how-to-use-animation-with-angular-6-675b19bc3496
https://medium.com/codingthesmartway-com-blog/angular-6-animations-from-scratch-76e110cba5fb

https://tympanus.net/codrops/2014/04/09/how-to-create-a-circular-progress-button/
https://github.com/dmytrodanylyk/circular-progress-button

https://stackblitz.com/angular/dmlypgmljpj
https://demo-077.codingthesmartway.com/

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
