### ISSUE TITLE
Filters: Loan Cards Filters

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#179]
### Loan Cards Filters
-Design a Filter Component for Requests - Activity - Address
-Consider using Material Design Components

**Refe:** 
![screen shot 2018-12-04 at 18 03 42](https://user-images.githubusercontent.com/12101846/49472754-0224a300-f7ef-11e8-9c04-cf7c96c4210b.jpg)

**Branch:** loan-cards-filter

**Comment by devbold** [comment]
### Filter Component

## Main Version
**Disabled State (at the beginning)**
![screen shot 2018-12-04 at 18 00 25](https://user-images.githubusercontent.com/12101846/49472868-4dd74c80-f7ef-11e8-958a-c9946fa01e61.jpg)
**Active State (on dirty)**
![screen shot 2018-12-04 at 17 59 58](https://user-images.githubusercontent.com/12101846/49473002-a1499a80-f7ef-11e8-9e40-55e0ff03d1e7.jpg)

## Advanced Version
![screen shot 2018-12-04 at 18 00 33](https://user-images.githubusercontent.com/12101846/49472957-8545f900-f7ef-11e8-8411-eeb1f732d4e0.jpg)

@Agusx1211 @NicolasMenendez

**Comment by devbold** [comment]
### Filter Component v2.0

## Main Version
**Disabled State (at the beginning)**
![screen shot 2018-12-05 at 20 00 02](https://user-images.githubusercontent.com/12101846/49549788-87c85180-f8c8-11e8-8d8b-1fb4a67d1dcb.jpg)
![screen shot 2018-12-05 at 20 00 34](https://user-images.githubusercontent.com/12101846/49549795-8dbe3280-f8c8-11e8-9d5d-985a54cf20f0.jpg)

**Active State (on dirty)**
![screen shot 2018-12-05 at 20 00 24](https://user-images.githubusercontent.com/12101846/49549801-94e54080-f8c8-11e8-80d9-460192c2b259.jpg)

## Advanced Version
![screen shot 2018-12-05 at 20 00 42](https://user-images.githubusercontent.com/12101846/49549803-9c0c4e80-f8c8-11e8-85bd-e18b8d47ce41.jpg)

@Agusx1211 @NicolasMenendez

**Comment by Agusx1211** [comment]
Done, #180 Congrats @devbold & @NicolasMenendez
