### ISSUE TITLE
Pagination to Sections for Loan Feeds

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#186]
### Pagination for Loan Feeds
-Add to Requests
-Add to Activity
-Add to Loans

![rcn-loans--requested-00](https://user-images.githubusercontent.com/12101846/49101495-14359d00-f255-11e8-98b4-50327d30689e.jpg)

**Refe:**
https://material.angular.io/components/paginator/overview
https://material.angular.io/components/table/overview
https://material.io/design/components/data-tables.html
**Branch:** pagination-to-feeds

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
