### ISSUE TITLE
Filters: Activity / Loans Filters 

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#189]
### Filter Component
-Add Filters to Activity section
-Add Filters to Loans section
-Change parameter duration for remaining
-Change parameter amount for paid
-Change parameter return for pending

**Refe:** #179

## Main Version
**Disabled State (at the beginning)**
![screen shot 2018-12-05 at 20 00 02](https://user-images.githubusercontent.com/12101846/49549788-87c85180-f8c8-11e8-8d8b-1fb4a67d1dcb.jpg)
![screen shot 2018-12-05 at 20 00 34](https://user-images.githubusercontent.com/12101846/49549795-8dbe3280-f8c8-11e8-9d5d-985a54cf20f0.jpg)

**Active State (on dirty)**
![screen shot 2018-12-05 at 20 00 24](https://user-images.githubusercontent.com/12101846/49549801-94e54080-f8c8-11e8-80d9-460192c2b259.jpg)

## Advanced Version
![screen shot 2018-12-05 at 20 00 42](https://user-images.githubusercontent.com/12101846/49549803-9c0c4e80-f8c8-11e8-85bd-e18b8d47ce41.jpg)

@Agusx1211 @NicolasMenendez

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
