### ISSUE TITLE
Redesign Profile

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#191]
### Profile Component
_Actual information_
-Approve Contract
-ACCOUNT INFORMATION --> Wallet address
-AUTHORIZE --> Approve contract

_Enhancements_
-Add more information
-Delete unsed information
-Move unfit info to another component
-Consideren redefine the component type if necessary

![screen shot 2018-12-27 at 12 41 21](https://user-images.githubusercontent.com/12101846/50485913-f2efda00-09d5-11e9-819e-562c64dbf5eb.jpg)

**Refe:** #73 #76

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
