### ISSUE TITLE
Redesign Balance

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#192]
### Balance Component
_Actual information_
-Balance on Header

_Enhancements_
-Redefine the component to something like Notification Component
-Add more information --> Add Icon to unlock the balance information
-Move unfit info to another component -- Move claim to a button
-Consideren redefine the component type if necessary --> Noti Comp example
-Delete unsed information 

![screen shot 2018-12-27 at 12 57 23](https://user-images.githubusercontent.com/12101846/50486105-00599400-09d7-11e9-95c3-282c5e39b5ab.jpg)

![screen shot 2018-12-27 at 12 56 14](https://user-images.githubusercontent.com/12101846/50486065-d607d680-09d6-11e9-9352-08685e1ccb74.jpg)

**Refe:** #158 #8 #165

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
