### ISSUE TITLE
Improve Lending Flow

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#195]
### Improve Lending Flow
_Actual information_
-Currency
-Amount
-Return

_Enhancements_
-Add Select Currency to update AMOUNT --> RETURN
-Take this currency selection for default lending CURRENCY
-Add more information
-Delete unsed information
-Move unfit info to another component
-Consideren redefine the component type if necessary

**Branch:**
checkout
**Docs:**
https://neilpatel.com/blog/40-checkout-page-strategies/
**Refe:**
Flip Card:
https://codepen.io/elmzarnsi/pen/XaWKjE
https://codepen.io/microsarme6943/pen/dXVLEr
![screen shot 2018-12-27 at 13 07 24](https://user-images.githubusercontent.com/12101846/50486349-61ce3280-09d8-11e9-9fd1-35a9d49c0bbf.jpg)

**Comment by devbold** [comment]
### Improve Lending Flow
_Enhancements_
-Scalable summaries
-Stepper for checkout process
-Insufficient founds warning label
-Insufficient founds disabled button feature
-Conversion graphics Summary for selection loan currency
-FAQs Frequently asked question tooltips (consider adding a new section for this)
-Collateral Summary to see the ERC721 collateral of the the loan

**Stepper for checkout process**
![screen shot 2019-01-08 at 11 01 54](https://user-images.githubusercontent.com/12101846/50835203-dab47f00-1334-11e9-8791-77c2ec690dc8.jpg)

**Insufficient founds warning label**
![screen shot 2019-01-08 at 11 03 06](https://user-images.githubusercontent.com/12101846/50835278-07689680-1335-11e9-8f58-f991227bc69e.jpg)

**Insufficient founds disabled button feature**
![screen shot 2019-01-08 at 11 03 16](https://user-images.githubusercontent.com/12101846/50835282-0b94b400-1335-11e9-8cbc-302c9900e3a3.jpg)

**Comment by devbold** [comment]
**Summury / Checkout v2 --> Loan Information v2.1**
![screen shot 2019-01-10 at 15 42 01](https://user-images.githubusercontent.com/12101846/50989552-70473e80-14ee-11e9-947a-aae5f6829aa0.jpg)
**Summury / Checkout v2 --> Loan Information v2.1**
![screen shot 2019-01-10 at 15 46 37](https://user-images.githubusercontent.com/12101846/50989812-1b57f800-14ef-11e9-9ad7-4062cedac599.jpg)
**Summury / Checkout v2 --> Collateral**
![screen shot 2019-01-10 at 15 42 23](https://user-images.githubusercontent.com/12101846/50989577-82c17800-14ee-11e9-819c-39c6bd1cccb3.jpg)
**Summury / Checkout v2 --> Benefits**
![screen shot 2019-01-10 at 15 44 26](https://user-images.githubusercontent.com/12101846/50989628-a71d5480-14ee-11e9-8f1a-deeb08c37237.jpg)
**Summury / Checkout v2 --> Conversion Graphic v2.1**
![screen shot 2019-01-10 at 15 46 04](https://user-images.githubusercontent.com/12101846/50989736-eea3e080-14ee-11e9-9dbb-e61ba2413b6e.jpg)
**Summury / Checkout v2 --> Conversion Graphic v2.2**
![screen shot 2019-01-10 at 15 46 20](https://user-images.githubusercontent.com/12101846/50989784-07ac9180-14ef-11e9-8e2f-e92485d1bd0b.jpg)
**Summury / Checkout v2 --> Conversion Graphic v2.3**
![screen shot 2019-01-10 at 15 48 21](https://user-images.githubusercontent.com/12101846/50989840-2f9bf500-14ef-11e9-9957-36b5fa80ba29.jpg)

**Comment by devbold** [comment]
**Summary / Checkout v3 --> Loan Information v1**
![screen shot 2019-01-11 at 18 08 42](https://user-images.githubusercontent.com/12101846/51059722-f6858280-15cb-11e9-8980-75dc0189f478.jpg)
**Summary / Checkout v3 --> Collateral v1**
![screen shot 2019-01-11 at 18 07 18](https://user-images.githubusercontent.com/12101846/51059739-fe452700-15cb-11e9-92dc-dfb4176ff0d1.jpg)
**Summary / Checkout v3 --> Benefits v1**
![screen shot 2019-01-11 at 18 07 36](https://user-images.githubusercontent.com/12101846/51059750-04d39e80-15cc-11e9-9ade-d8470af01b37.jpg)
**Summary / Checkout v3 --> Conversion Graphic v1**
![screen shot 2019-01-11 at 18 07 50](https://user-images.githubusercontent.com/12101846/51059764-1ae15f00-15cc-11e9-84b7-de0aca0f0add.jpg)

**Comment by devbold** [comment]
**Summary / Checkout v3 --> Conversion Graphic v3**
![screen shot 2019-01-14 at 11 41 30](https://user-images.githubusercontent.com/12101846/51119522-ddf6b180-17f1-11e9-96e1-f564568c66dd.jpg)
**Summary / Checkout v3 --> Conversion Graphic v4**
![screen shot 2019-01-14 at 11 41 45](https://user-images.githubusercontent.com/12101846/51119527-e222cf00-17f1-11e9-97b4-9dc120bf0200.jpg)
**Summary / Checkout v3 --> Conversion Graphic v5**
![screen shot 2019-01-14 at 11 41 59](https://user-images.githubusercontent.com/12101846/51119543-e7801980-17f1-11e9-9b55-b25ab2364b13.jpg)

**Comment by devbold** [comment]
**Summary / Checkout v4 --> Loan Information v1**
![rcn-loans--checkout-v2-01](https://user-images.githubusercontent.com/12101846/51133475-d8aa5e80-1813-11e9-960c-ccfbc7926714.jpg)
**Summary / Checkout v4 --> Loan Information v1 Details**
![rcn-loans--checkout-v2-02](https://user-images.githubusercontent.com/12101846/51133476-d8aa5e80-1813-11e9-873d-31fdbf5b3f51.jpg)
**Summary / Checkout v4 --> Collateral v1**
![rcn-loans--checkout-v2-03](https://user-images.githubusercontent.com/12101846/51133477-d8aa5e80-1813-11e9-94f8-b297d127e5dc.jpg)
**Summary / Checkout v4 --> Benefits v1**
![rcn-loans--checkout-v2-04](https://user-images.githubusercontent.com/12101846/51133478-d942f500-1813-11e9-8205-4223897de573.jpg)
**Summary / Checkout v4 --> Conversion Graphics v1**
![rcn-loans--checkout-v2-05](https://user-images.githubusercontent.com/12101846/51133479-d942f500-1813-11e9-9552-c61a2e1ecca3.jpg)

**Comment by devbold** [comment]
**Summary / Checkout v5 --> Loan Information v1**
![rcn-loans--checkout-v4-01](https://user-images.githubusercontent.com/12101846/51194045-07ced780-18c9-11e9-9188-6c2d8acae691.jpg)
**Summary / Checkout v5 --> Loan Information v1 Details**
![rcn-loans--checkout-v4-02](https://user-images.githubusercontent.com/12101846/51194047-07ced780-18c9-11e9-8428-7c2b03a02e0f.jpg)
**Summary / Checkout v5 --> Collateral v1**
![rcn-loans--checkout-v4-03](https://user-images.githubusercontent.com/12101846/51194048-07ced780-18c9-11e9-8989-8ffb5957c265.jpg)
**Summary / Checkout v5 --> Benefits v1**
![rcn-loans--checkout-v4-04](https://user-images.githubusercontent.com/12101846/51194049-08676e00-18c9-11e9-8f98-554ad8e9e388.jpg)

**Comment by devbold** [comment]
**Lending Amount TO Expected Amount**
![screen shot 2019-01-18 at 10 14 47](https://user-images.githubusercontent.com/12101846/51389045-ef99cb00-1b09-11e9-9120-4f2f9ee439d8.jpg)

**Comment by devbold** [comment]
**Lending Amount TO Expected Amount**
Design variable to differentiate the expected return from guaranteed return
_When the user hover the card flips to unlock the Guaranteed Return_

![screen shot 2019-01-18 at 11 06 52](https://user-images.githubusercontent.com/12101846/51391837-ec0a4200-1b11-11e9-8293-6a86476fed07.jpg)
![screen shot 2019-01-18 at 11 12 07](https://user-images.githubusercontent.com/12101846/51391839-ec0a4200-1b11-11e9-83d3-508e7e7acbd7.jpg)

**Comment by devbold** [comment]
**Lending Amount TO Expected Amount**
Design variable to differentiate the expected return from guaranteed return
_While the user is hovering, the card flips to unlock the Guaranteed Return_

![screen shot 2019-01-18 at 11 21 10](https://user-images.githubusercontent.com/12101846/51392256-38a24d00-1b13-11e9-9a66-bc7552548ed2.jpg)
![screen shot 2019-01-18 at 11 21 27](https://user-images.githubusercontent.com/12101846/51392257-38a24d00-1b13-11e9-9344-d67f6f81a5b2.jpg)

**Comment by devbold** [comment]
**Lending Amount TO Expected Amount**
Design variable from **@marianela** to differentiate the expected return from guaranteed return
_While the user is hovering, the card flips to unlock the Guaranteed Return_

![screen shot 2019-01-18 at 11 32 49](https://user-images.githubusercontent.com/12101846/51392939-350fc580-1b15-11e9-82a5-d357721101bd.jpg)
![screen shot 2019-01-18 at 11 32 56](https://user-images.githubusercontent.com/12101846/51392941-350fc580-1b15-11e9-8d6a-89ababbf0448.jpg)

**Comment by devbold** [comment]
**Lending Amount TO Expected Amount**
Design variable to differentiate the expected return from guaranteed return
_While the user is hovering, the card flips to unlock the Guaranteed Return_

![screen shot 2019-01-18 at 11 37 34](https://user-images.githubusercontent.com/12101846/51393028-7acc8e00-1b15-11e9-9779-0a4357db7e67.jpg)

**Comment by devbold** [comment]
**Lending Amount TO Expected Amount**
Design variable to differentiate the expected return from guaranteed return
_While the user is hovering, the card flips to unlock the Guaranteed Return_

![screen shot 2019-01-18 at 11 45 32](https://user-images.githubusercontent.com/12101846/51393494-95533700-1b16-11e9-94b9-3841257793f9.jpg)

**Comment by devbold** [comment]
**Expected Amount Tooltip**
Design variable toexpected return FAQS
_While the user is hovering, the tooltip unlock the Expected FAQS_

![screen shot 2019-01-18 at 11 49 42](https://user-images.githubusercontent.com/12101846/51393784-5671b100-1b17-11e9-95df-6ab029213d8a.jpg)

**Comment by devbold** [comment]
**Expected Amount Tooltip**
Design variable to expected return & guaranteed FAQS
_While the user is hovering, the tooltip unlock the returning FAQS_

![screen shot 2019-01-18 at 11 56 02](https://user-images.githubusercontent.com/12101846/51394044-14953a80-1b18-11e9-89b0-49483f17f343.jpg)
![screen shot 2019-01-18 at 11 55 06](https://user-images.githubusercontent.com/12101846/51394046-16f79480-1b18-11e9-9971-33b15fad24bc.jpg)

**Comment by devbold** [comment]
**Return Amount Tooltip**
Design variable to expected return & guaranteed FAQS, also considering the flipping action
_While the user is hovering, the tooltip unlock the returning FAQS_
_When the user clicks the flip button, the card flips to unlock the Guaranteed Return_

![screen shot 2019-01-18 at 12 27 24](https://user-images.githubusercontent.com/12101846/51395955-d3535980-1b1c-11e9-86c5-f323c1e1ef0c.jpg)

**Comment by devbold** [comment]
**Return Amount**
Design variable to expected return & guaranteed user interaction
_The Icon invites the user to hover and unlock the tooltip with the returning FAQS_
_The edge of a sheet invites the user to pull it into view the Guaranteed Return_

![screen shot 2019-01-18 at 13 35 13](https://user-images.githubusercontent.com/12101846/51400123-5e851d00-1b26-11e9-9c57-ae9b4ac33517.jpg)

**Comment by devbold** [comment]
**Return Amount**
Design variable to expected return & guaranteed user interaction
_The Icon invites the user to hover and unlock the tooltip with the returning FAQS_
_The edge of a sheet invites the user to pull it into view the Guaranteed Return_

![screen shot 2019-01-18 at 14 43 36](https://user-images.githubusercontent.com/12101846/51403537-82992c00-1b2f-11e9-8825-e5ff1adb744b.jpg)

**Comment by devbold** [comment]
**Lending Currency**
Design variable for Lending Currency Selection user interaction
_The slide toggle lock Icon invites the user to click and unlock another lending currency_
_The slide toggle spinner shows the user that hi is unlocking another lending currency_

![screen shot 2019-01-18 at 15 17 02](https://user-images.githubusercontent.com/12101846/51407769-921e7200-1b3b-11e9-9427-491b6edddec9.jpg)
![screen shot 2019-01-18 at 15 17 18](https://user-images.githubusercontent.com/12101846/51407773-95196280-1b3b-11e9-94b3-b5520cb9fcda.jpg)
![screen shot 2019-01-18 at 15 17 29](https://user-images.githubusercontent.com/12101846/51407781-977bbc80-1b3b-11e9-825d-7a154e4a498e.jpg)
![screen shot 2019-01-18 at 15 17 45](https://user-images.githubusercontent.com/12101846/51407789-99de1680-1b3b-11e9-9e06-6df8efdcb2d9.jpg)

**Comment by devbold** [comment]
**Slide Toggle Set**
![screen shot 2019-01-18 at 15 17 59](https://user-images.githubusercontent.com/12101846/51407807-a2cee800-1b3b-11e9-9ac1-6416b435fa13.jpg)

**Comment by devbold** [comment]
**Lending Currency**
Design proposal for Lending Currency Selection user interaction
_The slide toggle lock Icon invites the user to click and unlock another lending currency_
_The slide toggle spinner shows the user that hi is unlocking another lending currency_

![screen shot 2019-01-18 at 15 18 09](https://user-images.githubusercontent.com/12101846/51407954-0b1dc980-1b3c-11e9-9f17-4d9f704e6ac8.jpg)
![screen shot 2019-01-18 at 15 18 20](https://user-images.githubusercontent.com/12101846/51407956-0ce78d00-1b3c-11e9-93bc-1fe32387f9dd.jpg)
![screen shot 2019-01-18 at 16 17 16](https://user-images.githubusercontent.com/12101846/51408127-8bdcc580-1b3c-11e9-8c6c-3ab05a4aac1a.jpg)

**Comment by devbold** [comment]
**Lending Currency**
Design proposal for Lending Currency Selection user interaction
_The slide toggle lock Icon invites the user to click and unlock another lending currency_
_The slide toggle spinner shows the user that hi is unlocking another lending currency_
_The slide toggle display a snackbar showing you the metamask transaction information_

![screen shot 2019-01-18 at 16 18 38](https://user-images.githubusercontent.com/12101846/51408207-bb8bcd80-1b3c-11e9-96b9-9e012bd23b2c.jpg)

**Comment by devbold** [comment]
**Checkout -- Loan Information**
Design proposal for Checkout -- Loan Information

_The Icon invites the user to hover and unlock the tooltip with the returning FAQS_
_The edge of a sheet invites the user to pull it into view the Guaranteed Return_

_The slide toggle lock Icon invites the user to click and unlock another lending currency_
_The slide toggle spinner shows the user that hi is unlocking another lending currency_
_The slide toggle display a snackbar showing you the metamask transaction information_

![screen shot 2019-01-21 at 12 49 29](https://user-images.githubusercontent.com/12101846/51484735-14e14000-1d7b-11e9-968c-8cb162bead49.jpg)

**Comment by devbold** [comment]
**Checkout -- Loan Information**
Design proposal for Checkout -- Loan Information

_The Icon invites the user to hover and unlock the tooltip with the returning FAQS_
_The edge of a sheet invites the user to pull it into view the Guaranteed Return_

_The slide toggle lock Icon invites the user to click and unlock another lending currency_
_The slide toggle spinner shows the user that hi is unlocking another lending currency_
_The slide toggle display a snackbar showing you the metamask transaction information_

![screen shot 2019-01-21 at 12 45 17](https://user-images.githubusercontent.com/12101846/51484975-b1a3dd80-1d7b-11e9-820e-9486fa2878aa.jpg)

**Comment by devbold** [comment]
**Checkout -- Loan Information**
Design proposal for Checkout -- Loan Information

_The Icon invites the user to hover and unlock the tooltip with the returning FAQS_
_The edge of a sheet invites the user to pull it into view the Guaranteed Return_

_The slide toggle lock Icon invites the user to click and unlock another lending currency_
_The slide toggle spinner shows the user that hi is unlocking another lending currency_
_The slide toggle display a snackbar showing you the metamask transaction information_

![screen shot 2019-01-21 at 12 45 31](https://user-images.githubusercontent.com/12101846/51484989-bbc5dc00-1d7b-11e9-8594-ab41d7d2b729.jpg)

**Comment by devbold** [comment]
**Checkout -- Collateral Information**
Design proposal for Checkout -- Collateral Information

_The Collateral tab shows the user the Collateral he can be creditor in case the borrower defaults_

![screen shot 2019-01-21 at 12 45 42](https://user-images.githubusercontent.com/12101846/51485129-165f3800-1d7c-11e9-83aa-54b30bbc27f5.jpg)

**Comment by devbold** [comment]
**Checkout -- Loan Information Mobile**
Design proposal for Checkout -- Loan Information Mobile

_The card label invites the user to click and unlock the animation that shows card information_
_The edge of a sheet invites the user to pull it into view the Guaranteed Return_

_The slide toggle lock Icon invites the user to click and unlock another lending currency_
_The slide toggle spinner shows the user that hi is unlocking another lending currency_
_The slide toggle display a snackbar showing you the metamask transaction information_

**Refe:**
https://material.io/design/motion/speed.html#easing
https://medium.com/google-design/motion-design-doesnt-have-to-be-hard-33089196e6c2
https://speckyboy.com/html-css-examples-of-material-design-in-action/
https://stackoverflow.com/questions/42176008/how-to-implement-in-css-material-design-motion

**Comment by devbold** [comment]
**Checkout -- Loan Information Mobile**
Design proposal for Checkout -- Loan Information Mobile

_The card label invites the user to click and unlock the animation that shows card information_
_The edge of a sheet invites the user to pull it into view the Guaranteed Return_

_The slide toggle lock Icon invites the user to click and unlock another lending currency_
_The slide toggle spinner shows the user that hi is unlocking another lending currency_
_The slide toggle display a snackbar showing you the metamask transaction information_

![screen shot 2019-01-24 at 14 31 28](https://user-images.githubusercontent.com/12101846/51696668-c46d1b00-1fe4-11e9-911e-045d03a521ad.jpg)


**Checkout -- Loan Information Mobile**
Design proposal for Checkout -- Loan Properties Animation Mobile

![screen shot 2019-01-24 at 13 20 14](https://user-images.githubusercontent.com/12101846/51696693-cfc04680-1fe4-11e9-9ad3-260a4535a664.jpg)

**Checkout -- Loan Information Mobile**
Design proposal for Checkout -- Loan Properties Information Mobile

![screen shot 2019-01-24 at 13 20 23](https://user-images.githubusercontent.com/12101846/51698170-4dd21c80-1fe8-11e9-9d5e-34abae3656fe.jpg)


**Checkout -- Loan Information Mobile**
Design proposal for Checkout -- Lending Information Mobile

![screen shot 2019-01-24 at 13 20 45](https://user-images.githubusercontent.com/12101846/51698221-6d694500-1fe8-11e9-8df1-3f23cd304c69.jpg)


**Checkout -- Loan Collateral Mobile**
Design proposal for Checkout -- Lending Information Mobile

![screen shot 2019-01-24 at 13 20 59](https://user-images.githubusercontent.com/12101846/51698293-92f64e80-1fe8-11e9-9df4-8bebe75b0160.jpg)


**Checkout -- Loan Cosigner Mobile**
Design proposal for Checkout -- Lending Information Mobile

![screen shot 2019-01-24 at 13 21 08](https://user-images.githubusercontent.com/12101846/51698358-b3260d80-1fe8-11e9-9f7d-67596698c5e7.jpg)


**Refe:**
https://material.io/design/motion/speed.html#easing
https://medium.com/google-design/motion-design-doesnt-have-to-be-hard-33089196e6c2
https://speckyboy.com/html-css-examples-of-material-design-in-action/
https://codepen.io/agirton/pen/QwWzJd
https://stackoverflow.com/questions/42176008/how-to-implement-in-css-material-design-motion

**Comment by devbold** [comment]
**Checkout -- Loan Information Mobile**
Design proposal for Checkout -- Loan Information Mobile

_The card label invites the user to click and unlock the animation that shows card information_
_The edge of a sheet invites the user to pull it into view the Guaranteed Return_

_The slide toggle lock Icon invites the user to click and unlock another lending currency_
_The slide toggle spinner shows the user that hi is unlocking another lending currency_
_The slide toggle display a snackbar showing you the metamask transaction information_

![rcn-loans--checkout-v5-01](https://user-images.githubusercontent.com/12101846/51771346-7ed54e80-20c7-11e9-91d0-0f252abc2568.jpg)
![rcn-loans--checkout-v5-02](https://user-images.githubusercontent.com/12101846/51771354-83016c00-20c7-11e9-9442-1e21af9a904d.jpg)
![rcn-loans--checkout-v5-03](https://user-images.githubusercontent.com/12101846/51771362-85fc5c80-20c7-11e9-8d59-411a97e00723.jpg)
![rcn-loans--checkout-v5-04](https://user-images.githubusercontent.com/12101846/51771364-885eb680-20c7-11e9-8164-c0d7cde58f22.jpg)

**Checkout -- Loan Information Mobile**
Design proposal for Checkout -- Loan Properties Animation Mobile
![rcn-loans--checkout-v5-05](https://user-images.githubusercontent.com/12101846/51771372-8c8ad400-20c7-11e9-806a-2464af8c39b1.jpg)


**Checkout -- Loan Properties Mobile**
Design proposal for Checkout -- Loan Properties Information Mobile
![rcn-loans--checkout-v5-06](https://user-images.githubusercontent.com/12101846/51771383-97ddff80-20c7-11e9-8374-adfa0f1b2b51.jpg)


**Checkout -- Loan Information Mobile**
Design proposal for Checkout -- Lending Information Mobile
![rcn-loans--checkout-v5-07](https://user-images.githubusercontent.com/12101846/51771441-bba14580-20c7-11e9-88c6-b36b6828ed1b.jpg)


**Checkout -- Collateral Information Mobile**
Design proposal for Checkout -- Collateral Information Mobile
![rcn-loans--checkout-v5-08](https://user-images.githubusercontent.com/12101846/51771469-d96eaa80-20c7-11e9-8e81-b4ae0322f3cb.jpg)


**Checkout -- Cosigner Information Mobile**
Design proposal for Checkout -- Cosigner Information Mobile
![rcn-loans--checkout-v5-09](https://user-images.githubusercontent.com/12101846/51771542-12a71a80-20c8-11e9-85e5-4418f9f042ff.jpg)


**Refe:**
https://material.io/design/motion/speed.html#easing
https://material.io/design/motion/choreography.html#sequencing
https://medium.com/google-design/motion-design-doesnt-have-to-be-hard-33089196e6c2
https://speckyboy.com/html-css-examples-of-material-design-in-action/
https://codepen.io/agirton/pen/QwWzJd
https://stackoverflow.com/questions/42176008/how-to-implement-in-css-material-design-motion
https://material.io/archive/guidelines/patterns/scrolling-techniques.html#

**Comment by devbold** [comment]
**Checkout -- Loan Information Mobile**
Design proposal for Checkout -- Loan Information Mobile

_The card label invites the user to click and unlock the animation that shows card information_
_The edge of a sheet invites the user to pull it into view the Guaranteed Return_

_The slide toggle lock Icon invites the user to click and unlock another lending currency_
_The slide toggle spinner shows the user that hi is unlocking another lending currency_
_The slide toggle display a snackbar showing you the metamask transaction information_

![rcn-loans--checkout-v6-01](https://user-images.githubusercontent.com/12101846/51771560-28b4db00-20c8-11e9-91be-ecc0bdf505c3.jpg)
![rcn-loans--checkout-v6-02](https://user-images.githubusercontent.com/12101846/51771561-28b4db00-20c8-11e9-88e7-6e80ee2d36a3.jpg)
![rcn-loans--checkout-v6-03](https://user-images.githubusercontent.com/12101846/51771562-28b4db00-20c8-11e9-8b30-dbf4840855e5.jpg)


**Checkout -- Loan Information Mobile**
Design proposal for Checkout -- Loan Properties Animation Mobile
![rcn-loans--checkout-v5-05](https://user-images.githubusercontent.com/12101846/51771372-8c8ad400-20c7-11e9-806a-2464af8c39b1.jpg)


**Checkout -- Loan Properties Mobile**
Design proposal for Checkout -- Loan Properties Information Mobile
![rcn-loans--checkout-v5-06](https://user-images.githubusercontent.com/12101846/51771383-97ddff80-20c7-11e9-8374-adfa0f1b2b51.jpg)


**Checkout -- Loan Information Mobile**
Design proposal for Checkout -- Lending Information Mobile
![rcn-loans--checkout-v5-07](https://user-images.githubusercontent.com/12101846/51771441-bba14580-20c7-11e9-88c6-b36b6828ed1b.jpg)


**Checkout -- Collateral Information Mobile**
Design proposal for Checkout -- Collateral Information Mobile
![rcn-loans--checkout-v5-08](https://user-images.githubusercontent.com/12101846/51771469-d96eaa80-20c7-11e9-8e81-b4ae0322f3cb.jpg)


**Checkout -- Cosigner Information Mobile**
Design proposal for Checkout -- Cosigner Information Mobile
![rcn-loans--checkout-v5-09](https://user-images.githubusercontent.com/12101846/51771542-12a71a80-20c8-11e9-85e5-4418f9f042ff.jpg)


**Refe:**
https://material.io/design/motion/speed.html#easing
https://material.io/design/motion/choreography.html#sequencing
https://medium.com/google-design/motion-design-doesnt-have-to-be-hard-33089196e6c2
https://speckyboy.com/html-css-examples-of-material-design-in-action/
https://codepen.io/agirton/pen/QwWzJd
https://stackoverflow.com/questions/42176008/how-to-implement-in-css-material-design-motion
https://material.io/archive/guidelines/patterns/scrolling-techniques.html#

**Comment by devbold** [comment]
**Checkout -- Loan Information**
Design proposal for Checkout -- Loan Information

_The card label invites the user to click and unlock the animation that shows card information_
_The edge of a sheet invites the user to pull it into view the Guaranteed Return_

_The slide toggle lock Icon invites the user to click and unlock another lending currency_
_The slide toggle spinner shows the user that hi is unlocking another lending currency_
_The slide toggle display a snackbar showing you the metamask transaction information_

![screen shot 2019-01-28 at 14 28 30](https://user-images.githubusercontent.com/12101846/51856677-095bbf00-230f-11e9-9242-8df41d5c8830.jpg)
![screen shot 2019-01-28 at 15 12 29](https://user-images.githubusercontent.com/12101846/51856746-37d99a00-230f-11e9-859f-90b395e816ce.jpg)
![screen shot 2019-01-28 at 15 12 37](https://user-images.githubusercontent.com/12101846/51856747-37d99a00-230f-11e9-8f8c-c1bbcd645a4f.jpg)
![screen shot 2019-01-28 at 15 12 47](https://user-images.githubusercontent.com/12101846/51856748-37d99a00-230f-11e9-9ade-fe1cb2cce15c.jpg)


**Checkout -- Loan Properties Mobile**
Design proposal for Checkout -- Loan Properties Information Mobile
![screen shot 2019-01-28 at 15 07 12](https://user-images.githubusercontent.com/12101846/51856808-60fa2a80-230f-11e9-86bf-92ef2c9eea7f.jpg)


**Checkout -- Collateral ^Information Mobile**
![Uploading Screen Shot 2019-01-28 at 15.10.42.jpg…]()


**Checkout -- Information Mobile**


**Refe:**
https://material.io/design/motion/speed.html#easing
https://material.io/design/motion/choreography.html#sequencing
https://medium.com/google-design/motion-design-doesnt-have-to-be-hard-33089196e6c2
https://speckyboy.com/html-css-examples-of-material-design-in-action/
https://codepen.io/agirton/pen/QwWzJd
https://stackoverflow.com/questions/42176008/how-to-implement-in-css-material-design-motion
https://material.io/archive/guidelines/patterns/scrolling-techniques.html#

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
