### ISSUE TITLE
Make an easy CopyPaste Address Interaction

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#204]
### Make an easy Copy past Address Interaction
-Copy the full user address on Loan Card
-Consider using copy to clipboard icon
https://fontawesome.com/icons/copy?style=regular
https://fontawesome.com/icons/clipboard?style=regular

**Branch:** copy-to-clipboard
**Refe:**
![screen shot 2019-01-03 at 17 22 20](https://user-images.githubusercontent.com/12101846/50659705-2e614a00-0f7c-11e9-8fc0-b863f2cae5b8.jpg)

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
