### ISSUE TITLE
Related Loans / Save for later

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#207]
### Save for later/favorites
-Let the lender save for later/favorites a loan
-Let him pick it up from profile later
-**Would be nice to add same Related Loans on the Checkout Lending too**

**Refe:**
![screen shot 2019-01-07 at 14 12 32](https://user-images.githubusercontent.com/12101846/50782281-5c010880-1286-11e9-9e89-ae68f2a617a8.jpg)

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
