### ISSUE TITLE
Show Main actions Flow graphic

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#208]
### Show Lending Flow graphic
_Actual information_
-Nothing

_Enhancements_
-Add timeline graphic showing the lending flow and any other main action on the Dapp
--Download Metamask
--Download Civic
--Sign up on Civic
--Scan QR to let Civic sign for you
--Lend
--Monitor your loans
-Consider adding FAQs section

**Refe:**
https://about.draw.io/features/examples/
**Simple graphic**
![2](https://user-images.githubusercontent.com/12101846/50837924-9c6e8e00-133b-11e9-9e26-ecd3b9ce5689.png)
**Complex graphic**
![3](https://user-images.githubusercontent.com/12101846/50837969-b4dea880-133b-11e9-87bd-68bece6571a8.jpg)
![4](https://user-images.githubusercontent.com/12101846/50838069-eb1c2800-133b-11e9-8e64-7eb5c0c4411a.jpg)

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
