### ISSUE TITLE
Add Price information to sidebar

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#218]
### Add Price information to sidebar
_Actual information_
-No princing information

_Enhancements_
-Delete duplicated information

**Refe:**
https://cdp.makerdao.com/
![screen shot 2019-01-21 at 11 55 00](https://user-images.githubusercontent.com/12101846/51481836-9af98880-1d73-11e9-9d88-16560d369e40.jpg)

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
