### ISSUE TITLE
RenderLastestTx() is not working properly

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#219]
### RenderLastestTx() is not working properly
_Actual information_
-RenderLastestTx() is not confirming the confirmedTxs when rendering lastest Txs

_Enhancements_
-renderLastestTx() must setTxFinished() of confirmedTxs but filter unconfirmed filter(c => !c.confirmedTx)

**Refe:**
![screen shot 2019-01-21 at 13 35 45](https://user-images.githubusercontent.com/12101846/51487962-13b41100-1d83-11e9-8585-85e28b857df5.jpg)

**Comment by NicolasMenendez** [comment]
Bug Fixed.
