### ISSUE TITLE
Performance and load time

### ISSUE THREAD

**Issue by Agusx1211** [ripio/rcn-loans#22]
Results obtained from Chrome Lighthouse analysis tool

Possible improvements:

* Eliminate render-blocking resources

![image](https://user-images.githubusercontent.com/12701942/42236522-6b0498c0-7efb-11e8-97f4-93950f5bba3e.png)

* Add preconnect or dns-prefetch resource hints 

![image](https://user-images.githubusercontent.com/12701942/42236602-a41d1a38-7efb-11e8-9087-1da5f3ee0954.png)
note: The use of a third-party origin to load the Decentraland logo should be removed

* Properly size Ripio & Decentraland logo
* Lazy-load Ripio & Decentraland logo
* Preload Google fonts
* Preload Material icons

**Comment by ignacioperezroca** [comment]
### Performance and load time
-Folder Structure optimazed for IMG & FONTS
-Images optimazed for web (72ppi)
-Properly size Ripio & Decentraland logo
-Preload Google fonts
-Preload Material icons
-Preload Font Awesome

**Comment by ignacioperezroca** [comment]
### Performance and load time
-Scripts service Async load
-Async Link Stylesheet load

*Scripts service Async load --> Breaking error
Error: (in promise): civic is not defined
at new CivicService (civic.service.ts:10)
