### ISSUE TITLE
Dapp Tour

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#221]
### Dapp Tour
_Actual information_
-Nothing

_Enhancements_
Design a tour that illustrates the main processes that the user comes to operate in the dapp. It has to be easy, minimalist and simple so that in a few steps you can learn the Lend process. Use the material guidelines to solve it. It must contain at least one illustration for each step

1. Research
2. Material Design Analysis
3. Wireframes
4. Illustrations

*Refe:*
https://material.io/archive/guidelines/growth-communications/onboarding.html#onboarding-onboarding-models

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
