### ISSUE TITLE
Civic not working with Toshi

### ISSUE THREAD

**Issue by Agusx1211** [ripio/rcn-loans#25]
Currently Civic is not working with the Toshi app, Toshi does not handle the Civic Intent and it gets stuck on an invalid URL scheme error.

![image](https://user-images.githubusercontent.com/12701942/42241423-c8c179ec-7f0a-11e8-9097-2c175807b21a.png)
![image](https://user-images.githubusercontent.com/12701942/42241421-c55e4b9a-7f0a-11e8-9ce1-3ac5c264fa22.png)

Posible solutions:

1. Add compatibility Civic <-> Toshi
2. Find an alternative to Civic that works with Toshi

**Comment by ignacioperezroca** [comment]
### Reported
https://github.com/blockvis/civic-sip-php/issues/5
