### ISSUE TITLE
Provide a default gas price

### ISSUE THREAD

**Issue by Agusx1211** [ripio/rcn-loans#33]
Provide a custom default gas price when sending a transaction, currently, Metamask shows 0. 

Some third-party contracts require a specific gas price in order to work, so the service should be transaction-aware to deliver the correct price.

For most of the transactions, https://ethgasstation.info/ is a good source.

![image](https://user-images.githubusercontent.com/12701942/42525660-0346f0d8-8474-11e8-80a9-1a7a102ff0b2.png)

**Comment by rotcivegaf** [comment]
Now MetaMask provide a default gas price
