### ISSUE TITLE
Metrics: Google Analitics

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#38]
### Google Analitics
- Create Account ID
- Active Users
- Events (Lend, Transfer, View Detail, Forgive, Pay, Withdraw, Authorize, Buy, View Lender)

Branch: analitics

**Docs:**
https://developers.google.com/analytics/devguides/collection/analyticsjs/events
https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications
https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide
https://codeburst.io/using-google-analytics-with-angular-25c93bffaa18

**Comment by ignacioperezroca** [comment]
@Agusx1211 **Need Credentials**
- Create Account ID

**Comment by Agusx1211** [comment]
- [x] Create Account ID
- [x] Active Users
- [ ] Events (Lend, Transfer, View Detail, Forgive, Pay, Withdraw, Authorize, Buy, View Lender)

Merged https://github.com/ripio/rcn-loans/pull/69
