### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#39]
### Transaction History - Timeline
**Timeline**
**Transaction Icon**

-From
-To
-Beneficiary
-When
-Expires in
-Title: Action (Lend - Transfer - Forgive - Pay - Withdraw)
-Date
-Amount

**Branch: transaction-history**
**Refe:**
https://design4users.com/wp-content/uploads/2015/12/tubikstudio-motion-design-1.gif
**Docs:**
![screenshot_20180720-182656](https://user-images.githubusercontent.com/12101846/43022968-8c75c30c-8c3f-11e8-84b1-d3d7165e27cb.jpg)
T02G76EJ9-FBTN519HP/screenshot_20180720-182656.jpg

**Comment by ignacioperezroca** [comment]
![screenshot 2018-07-23 12 20 10](https://user-images.githubusercontent.com/12101846/43093750-4d620456-8e87-11e8-9026-cd4e952ad49d.png)
![screenshot 2018-07-23 12 20 27](https://user-images.githubusercontent.com/12101846/43093764-57a939fc-8e87-11e8-8cff-92a5a9c8b6b7.png)
![screenshot 2018-07-23 12 20 34](https://user-images.githubusercontent.com/12101846/43093765-57cd28f8-8e87-11e8-9496-bf73560a0a03.png)
![screenshot 2018-07-23 12 20 41](https://user-images.githubusercontent.com/12101846/43093766-57ef1832-8e87-11e8-901d-b6de5e67d0bd.png)
![screenshot 2018-07-23 12 20 56](https://user-images.githubusercontent.com/12101846/43093768-580ef72e-8e87-11e8-9ebb-ec38cdefe989.png)
![screenshot 2018-07-23 12 21 08](https://user-images.githubusercontent.com/12101846/43093769-5833540c-8e87-11e8-98a7-8b94782b45bf.png)
![screenshot 2018-07-23 12 29 16](https://user-images.githubusercontent.com/12101846/43093770-58573f34-8e87-11e8-9573-3b7979a50c3b.png)

**Comment by majd1239** [comment]
Love it^^

**Comment by devbold** [comment]
![4](https://user-images.githubusercontent.com/12101846/43157104-5fef215a-8f52-11e8-83bf-157aacbfe0fe.png)
![6](https://user-images.githubusercontent.com/12101846/43157106-603a8186-8f52-11e8-8678-db37ff9903c8.png)
![7](https://user-images.githubusercontent.com/12101846/43157107-6090db26-8f52-11e8-8273-540ce5e7176e.png)
![8](https://user-images.githubusercontent.com/12101846/43157108-60c0ae1e-8f52-11e8-97ec-c1853f729298.png)
![9](https://user-images.githubusercontent.com/12101846/43157109-60e413e0-8f52-11e8-9775-1143032ab8f8.png)
![10](https://user-images.githubusercontent.com/12101846/43157111-610bcb6a-8f52-11e8-854b-091c83e082a2.png)
![11](https://user-images.githubusercontent.com/12101846/43157113-612f5986-8f52-11e8-96c1-9d98519f8117.png)
![12](https://user-images.githubusercontent.com/12101846/43157114-61589d00-8f52-11e8-8691-686295a5ae95.png)

**Comment by devbold** [comment]
### Mobile
![rcnangulardapp--v00](https://user-images.githubusercontent.com/12101846/43282838-998c1d0e-90ed-11e8-980b-3c6d044ac3e7.jpg)
### Desktop
**v1**
![rcnangulardapp--v01](https://user-images.githubusercontent.com/12101846/43282839-99bbe03e-90ed-11e8-95dc-6caa8a2aae44.jpg)
**v2**
![rcnangulardapp--v02](https://user-images.githubusercontent.com/12101846/43282840-99df5d52-90ed-11e8-9e93-67dc51690a39.jpg)

**Comment by Agusx1211** [comment]
Great! Maybe we can add a little tooltip always visible containing a title and date for each item on the timeline. E.g.: "Paid 300 RCN"
