### ISSUE TITLE
View Detail: Add Navigation

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#40]
### View Detail - Add tabs on mobile component
**Split in two by tabs**
-Left
-Right

**Comment by ignacioperezroca** [comment]
![screenshot 2018-07-23 16 54 05](https://user-images.githubusercontent.com/12101846/43099618-1e1215da-8e99-11e8-9009-dff6e2d03db0.png)
![screenshot 2018-07-23 16 54 19](https://user-images.githubusercontent.com/12101846/43099619-1e36d9ba-8e99-11e8-83ce-6ed839ece878.png)

**Comment by ignacioperezroca** [comment]
@Agusx1211 What do you think about this new tabs organization?
If you agree change it to "enhancement" to do the development

**Comment by Agusx1211** [comment]
The V2 scheme is far more navigable than the current layout, and I think this is a great way to navigate to the loan history. :+1:
