### ISSUE TITLE
Display status of the loan in the card layout

### ISSUE THREAD

**Issue by Agusx1211** [ripio/rcn-loans#41]
When seeing a list of loans in the form of cards there is no way to know the current status of each of the loans. E.g.: Some loans can be "canceled" and should have a lower hierarchy. 

![image](https://user-images.githubusercontent.com/12701942/43313800-684ca3f4-9191-11e8-95eb-decfc4322b8c.png)

**Comment by devbold** [comment]
### Card Status
-Designing Templates process

**Refe:** https://material.io/design/interaction/states.html

**Comment by devbold** [comment]
### Template 1
-Designing Templates process

![rcn-loans--states-00](https://user-images.githubusercontent.com/12101846/45500523-368b4480-b755-11e8-8b38-8173ef9f3f36.jpg)
![rcn-loans--states-01](https://user-images.githubusercontent.com/12101846/45500525-368b4480-b755-11e8-8eb7-1fe777317e40.jpg)
![rcn-loans--states-02](https://user-images.githubusercontent.com/12101846/45500527-368b4480-b755-11e8-94e0-861687db3afb.jpg)
![rcn-loans--states-03](https://user-images.githubusercontent.com/12101846/45500528-3723db00-b755-11e8-867d-84274ed71a50.jpg)
![rcn-loans--states-04](https://user-images.githubusercontent.com/12101846/45500532-3ab76200-b755-11e8-9136-ac975444134c.jpg)

**Comment by devbold** [comment]
### Template 2
-Designing Templates process

![rcn-loans--states-05](https://user-images.githubusercontent.com/12101846/45500543-473bba80-b755-11e8-928a-7b79de8c4435.jpg)

**Comment by devbold** [comment]
### Template 3 
-Designing Templates process

![rcn-loans--states-06](https://user-images.githubusercontent.com/12101846/45500561-515db900-b755-11e8-8800-14e674404968.jpg)

**Comment by devbold** [comment]
### Template 4
-Designing Templates process

![rcn-loans--states-07](https://user-images.githubusercontent.com/12101846/45500585-60dd0200-b755-11e8-8311-ff1b298bdfd9.jpg)
![rcn-loans--states-08](https://user-images.githubusercontent.com/12101846/45500586-61759880-b755-11e8-9762-5cf2aeeb8207.jpg)
![rcn-loans--states-09](https://user-images.githubusercontent.com/12101846/45500587-61759880-b755-11e8-9aa6-b9c8df09282f.jpg)
![rcn-loans--states-10](https://user-images.githubusercontent.com/12101846/45500588-61759880-b755-11e8-8369-4a8c6767171f.jpg)

**Comment by devbold** [comment]
@Agusx1211 @rotcivegaf @rotcivegaf 
Which template do you thinks it shows in the better way, the loans state?

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
