### ISSUE TITLE
Request loans with collateral

### ISSUE THREAD

**Issue by Agusx1211** [ripio/rcn-loans#42]
Collateral crypto loans will enable any address on Ethereum to request a credit. This loan could be backed using any crypto asset, this could be an ERC-20 Token / ERC-721 Token or Ether, the ownership of this tokens is still transferable, but there are tied to the payment of the loan

The contracts are already being developed and the development can be followed in the Github repository https://github.com/ripio/rcn-pawn

**Comment by majd1239** [comment]
I think the rcn-pawn repo is private, it's not visible to me.
https://github.com/ripio/rcn-pawn gives me 404 http error

**Comment by nicolaswww** [comment]
This feature is developing at #365

**Comment by nicolaswww** [comment]
Released in 0.2.0 🚀
