### ISSUE TITLE
Show loans with address as borrower

### ISSUE THREAD

**Issue by Agusx1211** [ripio/rcn-loans#43]
The address view (https://testnet.rcn.loans/address/0x35d803f11e900fb6300946b525f0d08d1ffd4bed) should display not only the loans where the address is the Lender but also the loans with that address as the borrower. 

E.g.:
![image](https://user-images.githubusercontent.com/12701942/43314212-93508a60-9192-11e8-8381-8eec58313546.png)

**Comment by nicolaswww** [comment]
This feature is developing at #375

**Comment by nicolaswww** [comment]
Released in 0.2.0 🚀
