### ISSUE TITLE
Cancel loan request button

### ISSUE THREAD

**Issue by Agusx1211** [ripio/rcn-loans#45]
The "cancel" loan request button should be displayed in the loan detail if the user of the dApp is the borrower of the loan and if the loan is on the "request" status. 

This button should call the "destroy(id)" method of the engine and also cancel any cosigner liability tied to the loan, (E.g., a collateral deposit); this could imply multiple transactions on a single operation.

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
