### ISSUE TITLE
Create a 404 error page

### ISSUE THREAD

**Issue by Agusx1211** [ripio/rcn-loans#5]
The dapp does not implement a 404 error page, it should be visible when trying to access a nonexisting loan.

**Comment by ignacioperezroca** [comment]
<img width="1290" alt="screenshot 2018-06-28 17 18 21" src="https://user-images.githubusercontent.com/12101846/42097140-bf2cf4ea-7b8d-11e8-9e09-e6f2de4cbaab.png">

**Comment by ignacioperezroca** [comment]
Responsive UI
<img width="386" alt="screenshot 2018-06-29 17 51 55" src="https://user-images.githubusercontent.com/12101846/42114598-f0d41cb6-7bc5-11e8-89aa-867b429643d4.png">
![screenshot 2018-06-29 17 52 03](https://user-images.githubusercontent.com/12101846/42114599-f0fcf4d8-7bc5-11e8-99ee-f0b6ee401f40.png)
