### ISSUE TITLE
Loan detail back button

### ISSUE THREAD

**Issue by Agusx1211** [ripio/rcn-loans#72]
The back button on loan detail always leads to https://rcn.loans/requests

**branch:** navigation

**Comment by devbold** [comment]
Go back
-HandleGoBack() refurbished
-Code cleaning, unused router service
-Go back working still on refresh thanks to pushState

Refe:
https://angular.io/guide/router
https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries

Branch: not-found
#72
