### ISSUE TITLE
Misleading metamask alert - Lend

### ISSUE THREAD

**Issue by c0chi** [ripio/rcn-loans#79]
This happened a couple of times trying to lend.

However, the transaction was successfully mined 
https://etherscan.io/tx/0x50856a7d32ae5e2817c682fb726d89a36a35652b1cd6570b3d23071d6879773e

<img width="332" alt="screen shot 2018-08-17 at 20 45 44" src="https://user-images.githubusercontent.com/23640660/44283900-10f74200-a260-11e8-8154-ae0dbe674a0c.png">

**Comment by Agusx1211** [comment]
Loan: https://rcn.loans/loan/24

**Comment by Agusx1211** [comment]
Fixed on Oracle contract https://github.com/ripio/rcn-network/blob/master/contracts/examples/ReferenceOracle.sol
