### ISSUE TITLE
the > is not used and titles of data are blurred

### ISSUE THREAD

**Issue by rotcivegaf** [ripio/rcn-loans#84]
On the right, the arrowhead(>) is not used at all
Titles of Date, Approved by, Transaction, etc. dont see rigth
I'm using Version 66.0.3359.170 (Official Build) (64-bit)
In firefox quantum 61.0.1 (64-bit) the arrowhead dont see

![loan_history](https://user-images.githubusercontent.com/7088778/44592629-86e73600-a797-11e8-9508-a28dfba6aa9b.png)

**Comment by Agusx1211** [comment]
Split in 2 issues
