### ISSUE TITLE
The arrowhead(>) is not used

### ISSUE THREAD

**Issue by rotcivegaf** [ripio/rcn-loans#85]
On the right, the arrowhead(>) is not used at all
I'm using Version 66.0.3359.170 (Official Build) (64-bit)
In firefox quantum 61.0.1 (64-bit) the arrowhead dont see

![arrowhead](https://user-images.githubusercontent.com/7088778/44597984-e64d4200-a7a7-11e8-9336-1581a7861733.png)

**Comment by devbold** [comment]
### Arrow removed
-Arrow font chevron-right removed

**Branch:** transaction-history
