### ISSUE TITLE
Show amount of RCN loaned

### ISSUE THREAD

**Issue by PabloW92** [ripio/rcn-loans#89]
I've made a loan of 1000 ARS (argentine pesos), but of course the loan takes RCN tokens out of your wallet. When you see the loan details it shows you how many ARS you've loaned, but there's no information of how many RCN tokens specifically were taken off your wallet.
It would be nice to show the amount of RCN tokens you have initally given.

This would be usefull to know if you have gained or lost regarding to the amount of tokens (which can vary because in fluctuations in ARS in this case).
![screenshot from 2018-09-05 12-32-13](https://user-images.githubusercontent.com/11725171/45104367-5644bc00-b108-11e8-8c36-af049d64fbe2.png)

**Comment by devbold** [comment]
Design Propousal for Calculating an AMOUNT and RETURN depending on Currency selection
**V1**
![screen shot 2019-01-02 at 13 06 41](https://user-images.githubusercontent.com/12101846/50605712-e968e500-0ea1-11e9-9127-b9994eea34a7.jpg)

@Agusx1211

**Comment by camiladelaserna** [comment]
This issue belongs to the Design Department. It’s been transferred for further evaluation. In case of approval, a new issue will be created on this repository, with the tag ‘development’.
