### ISSUE TITLE
Remove Old-style style numerals

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#96]
### Change Raleway font for numbers to Roboto
-Impreve numbers view
-This may help to fix visual distortion in numbers with raleways

**Branch:** font-roboto

**Comment by Agusx1211** [comment]
Maybe a better replacement is https://h-ibaldo.github.io/Raleway_Fixed_Numerals/, this font removes the Old-style style numerals of Raleway

**Comment by devbold** [comment]
The typefaces of Google Fonts are free for commercial use. I cant find the policy of this font version
Since we dont not have to upload the fonts to the server, we dont not experience any strain from the fonts
Now we have 1 request of preload, with this set we'll multiplicate it be many requests

**Comment by Agusx1211** [comment]
> The typefaces of Google Fonts are free for commercial use. I cant find the policy of this font version
https://github.com/h-ibaldo/Raleway_Fixed_Numerals/blob/master/SIL%20Open%20Font%20License.txt

I wouldn't limit the options to fonts only available on Google fonts; it should be a way to workaround that performance hit.

Also, we should decide if we want to replace Raleway because we want to change the style of the site or because it has old-style numerals. 

If we only want to fix the old-style numerals, we should go with Rawline; if we're going to change the look of the site, we should make a desition about changing the font, and not one about removing the old-style numerals.

**Comment by devbold** [comment]
### Raleway + Roboto

Its valid to use up to 2 Fonts, and up to 4 fonts variables according to typografy fundamentals. We should consider adding a new font that could fusion properly with Raleway. I wouldnt remove Raleway, i think it has a good for display titles, but i think it would be usefull to combine it with a Roboto font. So we can start using it with numbers. Let me know if you've any other font you would like to add to this discussion so we can compare how it works with Raleway

![screen shot 2018-11-26 at 17 18 48](https://user-images.githubusercontent.com/12101846/49041454-083dd280-f1a4-11e8-8253-ee8df9df59e9.jpg)
![screen shot 2018-11-26 at 17 51 51](https://user-images.githubusercontent.com/12101846/49041462-0d028680-f1a4-11e8-9c2d-8086b848f92c.jpg)

### How to use them
![screen shot 2018-11-26 at 17 51 30](https://user-images.githubusercontent.com/12101846/49041586-636fc500-f1a4-11e8-986e-e6c004cab598.jpg)

### Variants Gilroy & Averta
![screen shot 2018-11-26 at 17 35 58](https://user-images.githubusercontent.com/12101846/49041515-31f6f980-f1a4-11e8-804f-9563cec28377.jpg)
![screen shot 2018-11-26 at 17 35 51](https://user-images.githubusercontent.com/12101846/49041520-37ecda80-f1a4-11e8-8119-34739fe87d67.jpg)

### Colors
![screen shot 2018-11-26 at 17 56 28](https://user-images.githubusercontent.com/12101846/49041710-b5b0e600-f1a4-11e8-851f-e108a206dbc7.jpg)

@Agusx1211

**Comment by Agusx1211** [comment]
@devbold Let's try tha scheme on the /requests page and see how it looks, but I like it

**Comment by Agusx1211** [comment]
Closed by #206
