### ISSUE TITLE
Active a snackbar on lending action

### ISSUE THREAD

**Issue by devbold** [ripio/rcn-loans#97]
### Active a snackbar on lending action
-Snackbar component
-This may help to the lender to be informed of any state changes of the action of lending

![rcn-loans--snackbar-02](https://user-images.githubusercontent.com/12101846/45559242-5172bd00-b818-11e8-9446-f0399bea0b07.jpg)

**Branch:** snackbar
**Refe:** https://material.io/design/components/snackbars.html#placement

**Comment by devbold** [comment]
### Active a snackbar on lending action
-Snackbar component
-This may help to the lender to be informed of any state changes of the action of lending
-Displayed on lend request
-Displayed on lend confirmed

**Comment by Agusx1211** [comment]
Closed by #98
